Replace yarn cache action
toptal/davinci-github-actions pull request #108
Opened 2023-01-26 17:53 UTC by waleedtt

[FX-NNNN]

### Description

Describe the changes and motivations for the pull request, unless evident from the title.

### How to test

- FIXME: Add the steps describing how to verify your changes

### Development checks

- [ ] Add changeset according to [guidelines](https://github.com/toptal/davinci-github-actions/blob/master/_docs/contribution/changeset-guidelines.md) (if needed)

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-anvil ping reviewers` - Ping FX team for review

</details>

2023-01-26 18:32 UTC, p0deje commented on yarn-install/action.yml
> +      uses: ./.github/cache_action/cache/
I assume we want to do so only if we're on the self-hosted runners, do we? 
Maybe we can guard this and previous actions to only be executed if `runner.name` indicates it's a self-hosted runner? At the very least, this should not be executed on public repositories.

2023-01-26 18:34 UTC, waleedtt commented on yarn-install/action.yml
> +      uses: ./.github/cache_action/cache/
Yes, I just forgot this point. I will update it

2023-01-27 16:46 UTC, dmaklygin commented on yarn-install/action.yml
> +      uses: ./.github/cache_action/cache/
Btw, how it should save a cache? It should save after packages installation?

2023-01-27 22:10 UTC, OndrejTuma reviewed
Please don't forget to add [changeset](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) here 🙇

2023-01-27 22:10 UTC, OndrejTuma commented on yarn-install/action.yml
> +    default: .
this can probably be ommited

2023-01-27 22:10 UTC, OndrejTuma commented on yarn-install/action.yml
> +    required: true
Should it be required? It would be breaking change. We can skip the steps with custom cache action when this token is not provided and devs can opt in to leverage it

2023-01-30 09:00 UTC, OndrejTuma commented on yarn-install/action.yml
> +      uses: ./.github/cache_action/cache/
good question

2023-01-31 10:41 UTC, waleedtt commented on yarn-install/action.yml
> +      uses: ./.github/cache_action/cache/
@dmaklygin It works the same way as the GitHub one. When we call this action, it tries to restore the cache from its key(restore keys). At the end of the workflow, it saves the path cache.

2023-02-01 07:03 UTC, dmaklygin commented on yarn-install/action.yml
> +      uses: ./.github/cache_action/cache/
Thank you for explanation!

2023-02-01 11:33 UTC, OndrejTuma requested changes

2023-02-01 11:33 UTC, OndrejTuma commented on yarn-install/action.yml
> +      id: node-modules-cache
@waleedtt I'm afraid you can't use the same `id` in multiple steps - you need change it and also adjust the output accordingly

2023-02-01 11:41 UTC, waleedtt commented on yarn-install/action.yml
> +      id: node-modules-cache
@OndrejTuma two outputs? but it will be hard to manage it from a usage point of view

2023-02-01 12:08 UTC, p0deje commented on yarn-install/action.yml
> +      id: node-modules-cache
There is just one output we need to propagate, so let's just merge them into one. Something like that should do the trick, but I haven't tested:

```yaml
- name: Merge cache-hit outputs
  id: node-modules-cache
  env:
    PUBLIC_CACHE_HIT: ${{ steps.public-node-modules-cache.outputs.cache-hit }}
    PRIVATE_CACHE_HIT: ${{ steps.private-node-modules-cache.outputs.cache-hit }}
  with:
    script: |
      const { PUBLIC_CACHE_HIT, PRIVATE_CACHE_HIT } = process.env
      core.setOutput(
        'cache-hit',
        JSON.parse(publicCacheHit) || JSON.parse(privateCacheHit)
      )
```

2023-02-01 12:39 UTC, OndrejTuma commented on yarn-install/action.yml
> +      id: node-modules-cache
To me it looks like you can [use expression in output](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#outputsoutput_idvalue) value 🤔 
So maybe it could be done easily by 
```yaml
outputs:
  cache-hit:
    description: 'Indicates an exact match was found for `node_modules` || boolean'
    value: ${{ steps.public-node-modules-cache.outputs.cache-hit || steps.private-node-modules-cache.outputs.cache-hit }}
```
But I also havent tested it

2023-02-01 12:42 UTC, OndrejTuma commented on yarn-install/action.yml
> +    description: Repository checkout access token `TOPTAL_REPOACCESSBOT_TOKEN`. Required for self hosted runners
One question, isnt `TOPTAL_DEVBOT_TOKEN` enough to use? I checked that in organization secrets we dont have `TOPTAL_REPOACCESSBOT_TOKEN`

2023-02-01 12:43 UTC, p0deje commented on yarn-install/action.yml
> +      id: node-modules-cache
@OndrejTuma I think outputs are always strings, so you can't `||` them. That's why I have `JSON.parse(...)` in the script.

2023-02-01 13:05 UTC, OndrejTuma commented on yarn-install/action.yml
> +      id: node-modules-cache
@p0deje  But you can use operators in expression. And both cache hits already are in string format, so its just a expression of `string1 || string2`. I tested it briefly and it seems to work

2023-02-01 14:17 UTC, p0deje commented on yarn-install/action.yml
> +      id: node-modules-cache
@OndrejTuma I guess it should work indeed when only one action is executed and the other is `null`. But what would that be if both actions are executed?

```
'false' || 'true'
```

2023-02-01 18:55 UTC, waleedtt commented on yarn-install/action.yml
> +    description: Repository checkout access token `TOPTAL_REPOACCESSBOT_TOKEN`. Required for self hosted runners
Most of the time `TOPTAL_DEVBOT_TOKEN` reaches its rate limits. We have kept this action safe by making a new token. Yes, we are allowing access to repositories that are migrated.

2023-02-02 10:01 UTC, dmaklygin commented on yarn-install/README.md
> +| `checkout-token`          | string |          |        | Repository checkout access token `TOPTAL_REPOACCESSBOT_TOKEN`. Required for self hosted runners command
if `TOPTAL_REPOACCESSBOT_TOKEN` is not specified, then after upgrading to the new GH Action version, job highly likely will be failed?

2023-02-02 10:14 UTC, waleedtt commented on yarn-install/README.md
> +| `checkout-token`          | string |          |        | Repository checkout access token `TOPTAL_REPOACCESSBOT_TOKEN`. Required for self hosted runners command
it shouldn't be, condition will not allow it to use the new action 

https://github.com/toptal/davinci-github-actions/pull/108/files#diff-794ba856f7cd887d12c3b9bbe69f56374290725c4eace480a3c0e075fcc79d9fR48

2023-02-02 10:16 UTC, dmaklygin commented on yarn-install/README.md
> +| `checkout-token`          | string |          |        | Repository checkout access token `TOPTAL_REPOACCESSBOT_TOKEN`. Required for self hosted runners command
Got it. Thanks for explanation!

2023-02-03 05:50 UTC, waleedtt commented on yarn-install/action.yml
> +      id: node-modules-cache
I have updated the changes, please have a review

2023-02-03 05:52 UTC, waleedtt commented on yarn-install/action.yml
> +      id: node-modules-cache
@p0deje there shouldn't be any chances of both executions. If any of the conditions fail, custom would not run
Custom action
`${{ inputs.checkout-token && contains(runner.name, 'inf-gha-runners-ci') }}`
Default
`${{ !contains(runner.name, 'inf-gha-runners-ci') || !inputs.checkout-token }}`

2023-02-03 05:53 UTC, waleedtt commented
@toptal-anvil ping reviewers

2023-02-03 10:44 UTC, waleedtt commented
@toptal-anvil ping reviewers

2023-02-03 11:40 UTC, dmaklygin approved these changes
Good work. there are still unresolved comments from @OndrejTuma. The rest is fine!

2023-02-03 16:07 UTC, p0deje commented on yarn-install/action.yml
> +      if: ${{ inputs.checkout-token && contains(runner.name, 'inf-gha-runners-ci') }}
You can omit surrounding `${{ }}` for `if:` conditions - https://docs.github.com/en/actions/learn-github-actions/expressions#about-expressions

2023-02-03 16:07 UTC, p0deje commented on yarn-install/README.md
> +| `checkout-token`          | string |          |        | Repository checkout access token `TOPTAL_REPOACCESSBOT_TOKEN`. Required for self hosted runners command
Let's replace `TOPTAL_REPOACCESSBOT_TOKEN` with `GITHUB_TOKEN` in documentation since it's a public repo.

2023-02-03 16:07 UTC, p0deje commented on yarn-install/action.yml
> +    description: Repository checkout access token `TOPTAL_REPOACCESSBOT_TOKEN`. Required for self hosted runners
Let's replace TOPTAL_REPOACCESSBOT_TOKEN with GITHUB_TOKEN in documentation since it's a public repo.

2023-02-03 16:07 UTC, p0deje commented on yarn-install/action.yml
> +      if: ${{ inputs.checkout-token && contains(runner.name, 'inf-gha-runners-ci') }}
You can omit surrounding ${{ }} for `if`: conditions.

2023-02-06 09:40 UTC, OndrejTuma approved these changes
Thanks, I think it looks and works correctly 👌 
Great work 🎉

2023-02-06 10:03 UTC, TomasSlama approved these changes
nice!

2023-02-06 10:55 UTC, merged