feat: [FX-3919] add create-jira-deployment GH Action
toptal/davinci-github-actions pull request #158
Opened 2023-04-20 13:11 UTC by dmaklygin

[FX-3919]

### Description

We need to create a reusable GH Action which creates and connects deployment with Jira ticket.

### How to test

- Use it in GH Workflow

### Development checks

- [ ] Add changeset according to [guidelines](https://github.com/toptal/davinci-github-actions/blob/master/_docs/contribution/changeset-guidelines.md) (if needed)

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-anvil ping reviewers` - Ping FX team for review

</details>

2023-04-20 14:25 UTC, dmaklygin commented
@toptal-anvil ping reviewers

2023-04-20 14:28 UTC, augustobmoura approved these changes
Looks really good! :+1:

2023-04-20 14:41 UTC, mkrl requested changes

2023-04-20 14:41 UTC, mkrl commented on create-jira-deployment/action.yml
> +    default: production
Should we default this to `production`? I feel like this should be a required parameter.
Looking across other environment names we have in Jira deployments, it's usually `product-name-environment`. So, leaving this out as optional risks the possibility of creating a generic "production" environment that is not following the naming convention.

2023-04-20 14:52 UTC, augustobmoura commented on create-jira-deployment/action.yml
> +    default: production
Maybe we don't provide a default? wdyt @dmaklygin? Make the variable required and the user should fill it

2023-04-20 14:52 UTC, augustobmoura commented on create-jira-deployment/action.yml
> +    default: production
It would make the user explicitly think about it

2023-04-20 14:58 UTC, dmaklygin commented on create-jira-deployment/action.yml
> +    default: production
Why so? Jira, understands only several environments: https://github.com/atlassian/github-for-jira/blob/main/docs/deployments.md#environment-mapping
It tries to guess the environment type from your environment name.
However, other environments, that are not recognized, it marks as a `Others`.

I don't think, this parameter should be required.

2023-04-20 15:11 UTC, mkrl commented on create-jira-deployment/action.yml
> +    default: production
Yes, and all the existing environments we have are labeled like this: `xxx-portal-staging`, `xxx-portal-production`, etc.
It will still be good enough to be recognized by Jira and at the same time it will follow a convention.
IMO it's better to have it forced to be specified instead of forgetting to name it and thinking something was deployed to "production".

Also (unrelated), but we could map our `temploy` to `testing` in `.jira/config.yml` so it won't be displayed as "other" (since there is no concept "temploy" in Jira).

2023-04-20 15:24 UTC, dmaklygin commented on create-jira-deployment/action.yml
> +    default: production
Actually, we do not have a convention. It's completely up to a team to choose the environment. 
We inherited this optional input from the external + we usually do such helpers to, for example: https://github.com/toptal/davinci-github-actions/blob/5a2eb19e1f33647e281becf1175d4c61abdef2b1/deploy-storybook/action.yml#L22

I still think, that required parameter is a vital parameter for successful running GH Action. The rest should be optional

2023-04-21 10:18 UTC, dmaklygin commented on create-jira-deployment/action.yml
> +        environment: ${{ inputs.toenvironmentken }}
what is it???

2023-04-21 10:18 UTC, mkrl approved these changes
Awesome job!

2023-04-21 10:26 UTC, merged