[FX-NULL] TBD
toptal/davinci-github-actions pull request #280
Opened 2024-02-09 12:01 UTC by sashuk

[FX-NNNN]

### Description

Describe the changes and motivations for the pull request, unless evident from the title.

### How to test

- FIXME: Add the steps describing how to verify your changes

### Development checks

- [ ] Add changeset according to [guidelines](https://github.com/toptal/davinci-github-actions/blob/master/_docs/contribution/changeset-guidelines.md) (if needed)

<details>
<summary>PR commands</summary>
<br />

List of available commands:

- `@toptal-anvil ping reviewers` - Ping FX team for review

</details>

2024-02-09 16:01 UTC, sashuk commented
@toptal-anvil ping reviewers

2024-02-12 08:34 UTC, sashuk commented
@toptal-anvil ping reviewers

2024-02-12 17:06 UTC, OleksandrNechai requested changes
Very cool testing section and great console logging 👍 I left a bunch of "clean code" comments. After improving on those, we can move on!

2024-02-13 15:50 UTC, sashuk commented on notify-jira-about-contribution/action.yml
> +        # Define function to extract major versions from PR title
@OleksandrNechai Removed, thanks!

2024-02-13 15:51 UTC, sashuk commented on notify-jira-about-contribution/action.yml
> +        new_major=""
@OleksandrNechai Addressed, thanks!

2024-02-13 15:51 UTC, sashuk commented on notify-jira-about-contribution/action.yml
> +          # Assign function parameter to a variable
@OleksandrNechai Removed, thanks!

2024-02-13 15:51 UTC, sashuk commented on notify-jira-about-contribution/action.yml
> +          pr_title=$1
@OleksandrNechai Done, thanks!

2024-02-13 15:52 UTC, sashuk commented on notify-jira-about-contribution/action.yml
> +          #   - "cut -d'.' -f1" extracts the first part of the version number
@OleksandrNechai Addressed, thanks!

2024-02-13 15:52 UTC, sashuk commented on notify-jira-about-contribution/action.yml
> +          old_major_value=$(echo "$pr_title" | grep --only-matching --extended-regexp 'from [0-9]+(\.[0-9]+)?' | cut -d' ' -f2 | cut -d'.' -f1)
@OleksandrNechai Addressed, thanks!

2024-02-13 15:53 UTC, sashuk commented on notify-jira-about-contribution/action.yml
> +        if [[ $isDependabot == "true" ]]; then
@OleksandrNechai Addressed, thanks! The code was rewritten in early exit approach

2024-02-13 15:54 UTC, sashuk commented on notify-jira-about-contribution/action.yml
> +          # Extracting the new major version using grep
@OleksandrNechai Comment was added, thanks!

2024-02-13 15:54 UTC, sashuk commented
@OleksandrNechai Thank you for the review and suggestions! I think code is ready for review, it was polished and it seems to be much more readable now.

2024-02-13 15:56 UTC, sashuk commented
@toptal-anvil ping reviewers

2024-02-13 16:06 UTC, TomasSlama approved these changes
I didn't test, but the code looks good!

2024-02-14 08:12 UTC, sashuk commented
@toptal-anvil ping reviewers

2024-02-14 08:12 UTC, OleksandrNechai approved these changes
Cool! Much better this time! 👍 We need to test carefully, I did not have time to analyse if logic makes sense. Code looks good now, so approving to not block PR as I am on vacation.

2024-02-14 08:12 UTC, OleksandrNechai commented on notify-jira-about-contribution/action.yml
> +          echo "result=true" >> $GITHUB_OUTPUT
Can we avoid nesting `if` here? It is confusing to see `echo "Pull request author is not a member of ${{ inputs.team }}"` as a result of `if [[ $isDependabotPullRequest == "false" ]]; then`. If not then maybe bash supports `&` in if statements?
i.e. maybe team check can be done first? seems like it is safe to exit right away if we have team member as an author

2024-02-14 08:12 UTC, OleksandrNechai commented on notify-jira-about-contribution/action.yml
> +          echo "No need to notify about dependency updates"
```suggestion
          echo "Although ths is dependabot PR, notifying about major dependabot updates is turned off. Exiting."
```

2024-02-14 08:12 UTC, OleksandrNechai commented on notify-jira-about-contribution/action.yml
> +          echo "Is not a major dependency update"
```suggestion
          echo "It's minor or patch update. We don't create tickets for those. Exiting."
```
Lets be positive? :)

2024-02-14 09:16 UTC, sashuk commented on notify-jira-about-contribution/action.yml
> +    description: Specifies if action should create Jira issues for major dependency updates (authored by dependabot)
@OleksandrNechai Added, thanks!

2024-02-14 09:16 UTC, sashuk commented on notify-jira-about-contribution/action.yml
> +          echo "Is not a major dependency update"
@OleksandrNechai Added, thanks!

2024-02-14 09:16 UTC, sashuk commented on notify-jira-about-contribution/action.yml
> +          echo "No need to notify about dependency updates"
@OleksandrNechai Added, thanks!

2024-02-14 09:21 UTC, sashuk commented on notify-jira-about-contribution/action.yml
> +          echo "result=true" >> $GITHUB_OUTPUT
@OleksandrNechai Early check on team membership was added, thanks!

2024-02-14 09:34 UTC, sashuk commented
@OleksandrNechai I've also added test `/notify-jira-about-contribution/should-create-jira-issue.test.sh` to test the logic to have more confidence

2024-02-14 09:34 UTC, merged

2024-02-14 13:42 UTC, OleksandrNechai reviewed
Very nice updates. I like the code now and the tests add indeed a lot of confidence! 👍